name: Run Script and Commit

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-script-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Execute Script
      run: pip install matplotlib pandas requests && python scrape.py && python plots.py

    - name: Commit Changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git diff --quiet || git commit -m "Update generated files" && git push
